### ISSUE TITLE
eric task week of 5/19

### ISSUE THREAD

**Issue by ebridge2** [Upward-Spiral-Science/fngs#1]
- [ ] get fMRI registration working
- [ ] deliverables: QC metrics from below pipeline (NOTE: this pipe leaves out reorientation):
  ![image](https://cloud.githubusercontent.com/assets/8883547/15366666/60ceaf88-1cf3-11e6-888d-a9c33d8a1e95.png)
  http://fcp-indi.github.io/docs/developer/workflows/func_preproc.html

**Comment by ebridge2** [comment]
things to decide: what do we want to leave out from CPAC (skullstripping, particularly, and they also don't provide any methods for slice-timing so we will need to look elsewhere for that)?

**Comment by ebridge2** [comment]
deliverable by monday:
- [ ] get a line for distribution of dice overlap of each subject containing C(t, 2) where t is number of time points, and overlap for all 4 metrics (AFNI, EDDY, F2G, Raw), 4 figures total

**Comment by jovo** [comment]
@gkiar @ebridge2 let's discuss tomorrow.

On Thu, May 19, 2016 at 6:01 PM, ebridge2 notifications@github.com wrote:

> deliverable by monday:
> - get a line for distribution of dice overlap of each subject
>   containing C(t, 2) where t is number of time points, and overlap for all 4
>   metrics (AFNI, EDDY, F2G, Raw), 4 figures total
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ugrad-data-design-team-0/issues/1#issuecomment-220458399

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by ebridge2** [comment]
@jovo I discussed with @gkiar earlier, I can relay what we talked about if
@gkiar doesn't have time

On Thu, May 19, 2016 at 9:07 PM, joshua vogelstein <notifications@github.com

> wrote:
> 
> @gkiar @ebridge2 let's discuss tomorrow.
> 
> On Thu, May 19, 2016 at 6:01 PM, ebridge2 notifications@github.com
> wrote:
> 
> > deliverable by monday:
> > - get a line for distribution of dice overlap of each subject
> >   containing C(t, 2) where t is number of time points, and overlap for all
> >   4
> >   metrics (AFNI, EDDY, F2G, Raw), 4 figures total
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/neurodata/ugrad-data-design-team-0/issues/1#issuecomment-220458399
> 
> ## 
> 
> the glass is all full: half water, half air.
> neurodata.io, jovo calendar
> <
> https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
> 
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ugrad-data-design-team-0/issues/1#issuecomment-220492850

## 

Eric Bridgeford
ericwb.me

**Comment by gkiar** [comment]
I have some time tomorrow to chat! @ebridge2 we'll be updating what we
talked about to do the "simplest possible thing" :)

## 

Greg Kiar gkiar07@gmail.com
