### ISSUE TITLE
FLIRT real data - followup after algorithms.md update

### ISSUE THREAD

**Issue by 02agarwalt** [Upward-Spiral-Science/fngs#100]
I think the real data for FLIRT falls under scenario 2 (no ground truth). However, I don't understand how discriminability plays a role here. The registration result for an input and a reference brain doesn't really relate to data-set wide discriminability, and if anything it decreases the discriminability, right? Because once registered, the input and reference are more similar.

**Comment by jovo** [comment]
the question is whether two scans from the *same* person are more similar to each other after FLIRT than they are before FLIRT.

does that help clarify?

perhaps you can propose language that makes that clear to you (assuming it does)

**Comment by ebridge2** [comment]
I think what tanay is saying is that, with FLIRT, let's say one subject has some anomaly that leads to failure regardless of the x,y,z and rotations for a particular subject. That is, any scan of the particular subject's head registers identically poorly. Propogate this over a dataset, and you have a bunch of scans that register identically to the other scans for that subject, but still ineffectively in the scope that they are just qualitatively a bad registration (ie, after registration, tissue that is supposed to be a particular brain area is not correct according to the template, but all of the scans for that one subject have the same poor tissue alignment so they still are the same regions themselves). When you perform timeseries analysis, the timeseries "per ROI" will just reflect such that each ROI for that subject may not actually be the ROI it's supposed to, so the difference you pick up when you do discriminability is not even necessarily the same brain tissue being compared. Does that make sense? Kinda hard to explain electronically.

**Comment by jovo** [comment]
hm, not to me.  "identical" doesn't ever hold true in real data.
let's discuss tomorrow via skype.
