### ISSUE TITLE
Due 2/27

### ISSUE THREAD

**Issue by ebridge2** [Upward-Spiral-Science/fngs#123]
#@ebridge2
- [x] make R package with all discriminability code, and several functions that will do everything while taking just a list of paths to appropriately-named folders containing datasets.  [discr repo](https://github.com/ebridge2/Discriminability)
NOTE: I have a shortened week due to a visit and interview Tuesday - Friday. 
- [x] talk with leo and decide a strategy for task fMRI analysis. Deliverable: notes from meeting, particularly several potential approaches to consider for investigation. [notes](https://github.com/NeuroDataDesign/fngs/blob/master/status/joint_embedding.md)

@ewalke31 
- [x] methods.md for epi_reg for distortion correction to determine usefulness for pipeline. By Thursday: look over lecture & references on epi_reg and attempt to run - ABANDONED
[pivot deliverable](http://neurodatadesign.github.io/fngs/ewok_weekly/glm/ewok_week_0227.html)

@02agarwalt 

 - [x] methods.md for epi_reg for fmri to t1/mprage registration. This will replace the "flirt only" combo, not the "flirt prior to running fnirt" combo for t1 to mni registration. By Thursday: attempt running epi-reg and bring questions for Greg. [Link](http://neurodatadesign.github.io/fngs/tanay/EPI_REG.html)

**Comment by gkiar** [comment]
@ebridge2:
  - 👌 

@ewalke31:
  - what is your monday deliverable? a methods.md implementing it or explaining why you couldn't?

@02agarwalt:
  - what is your monday deliverable? a methods.md implementing it or explaining why you couldn't?

**Comment by 02agarwalt** [comment]
edited @gkiar

**Comment by gkiar** [comment]
👌

**Comment by ebridge2** [comment]
@gkiar Thursday deliverable added; I won't be here Thursday so let me know what you think here or offline via slack.

**Comment by ewalke31** [comment]
updated @gkiar

**Comment by ewalke31** [comment]
@ewalke31: pivot- research denoising methods or other fmri processing strategy to investigate & deliverable: present paper with method, why i want to try, the point, why it will make it better (possibly investigate methods for task-based fmri that may differ from methods for resting fmri)
