### ISSUE TITLE
week of 6/20

### ISSUE THREAD

**Issue by ebridge2** [Upward-Spiral-Science/fngs#17]
- [x] update proposal document

@ebridge2: these things due by Thursday
- [x] full quality control results for KKI dataset (deliverable is a folder on google drive containing 7 figures and 1 statistical summary for each scan)
- [x] implement quality control from CPAC; figure out what they do differently from Harvard (deliverable is a three column spreadsheet, with unique from Harvard, overlap, and unique from CPAC)  
  https://docs.google.com/spreadsheets/d/14P_ot2f2XpJsINiRrOYN1FC_SDIyIsHRM2xzXqWDJU0/edit?usp=sharing
- [x] discriminability results for KKI dataset (figure showing distance matrix and discriminability, and another figure with intra vs inter subject kde and hellinger distance between the two)

All results are in the google drive; in the CoRR_results/FNGS folder.

by Monday:
- [x] pseudocode for deciding a way to compare spatial smoothing effectiveness, decide how/when to resample, how to compare before/after of registration properly

@ewalke31: by thursday
- [x] reproduce figures from PLDS project
  https://github.com/Upward-Spiral-Science/fngs/tree/gh-pages/ewok_weekly/plds
- [x] summarize ch. 4-7 of fmri data analysis book
  https://docs.google.com/document/d/1Zc2c_LaHTiV_oBmL9DxVZ-lbJJeZa6vQz_Y2MMZNYzI/edit?usp=sharing

**Comment by ebridge2** [comment]
TODOs 1 and 3 may take until Friday or weekend as NKI dataset (being used since it is isotropic while KKI is antisotropic) has far more timesteps than KKI (like 5x more timesteps per graph as the most reliable scans were TR = 645 ms), and the runs will not be up until tomorrow since I am modifying the QC pages extensively

**Comment by jovo** [comment]
:ok_hand:

On Tue, Jun 21, 2016 at 7:18 PM, ebridge2 notifications@github.com wrote:

> TODOs 1 and 3 may take until Friday or weekend as NKI dataset (being used
> since it is isotropic while KKI is antisotropic) has far more timesteps
> than KKI (like 5x more timesteps per graph as the most reliable scans were
> TR = 645 ms), and the runs will not be up until tomorrow since I am
> modifying the QC pages extensively
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Upward-Spiral-Science/fngs/issues/17#issuecomment-227600670,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcnwC8U93IJNa40Q6HK2cNnaU1uTFks5qOHE5gaJpZM4I6JRE
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
