### ISSUE TITLE
update ideas

### ISSUE THREAD

**Issue by ebridge2** [Upward-Spiral-Science/fngs#19]
- [x] jitter plot of x as slice number, y as MSE, color as before vs after (420 points per slice for KKI)
- [ ] histrograms for distortion correction based on correction maps

**Comment by ebridge2** [comment]
jitter plot looks super awesome and informative. The middle slices, as they are primarily occupied by brain tissue and not background noise, show the least error from image to image, which makes sense since the signals in KKI are relatively high compared to the background and the area to perimeter ratio is relatively high (meaning that errors along the perimeter, which is what we are looking for with motion correction compared to the s0 slice here that we motion correct to, will have less of an impact on overall MSE), however, the slices that have less brain material show greater difference between before and after since the brain tissue occupies a lower percentage of the image, so any errors along the perimeter will be more significant wrt the occupied region. 

![image](https://cloud.githubusercontent.com/assets/8883547/16326665/a6a2384e-3996-11e6-9991-b5f9b7a1d899.png)

**Comment by jovo** [comment]
cool.
is this R or Python?
use alpha level of < 1 so that we can see overlap,
and maybe make dots smaller...

On Thu, Jun 23, 2016 at 11:03 PM, ebridge2 notifications@github.com wrote:

> jitter plot looks super awesome and informative.
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/8883547/16326665/a6a2384e-3996-11e6-9991-b5f9b7a1d899.png
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Upward-Spiral-Science/fngs/issues/19#issuecomment-228246872,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcrk79gHU4AL9Kb7s4tNAtt3n1-Cuks5qO0jvgaJpZM4I7BES
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by ebridge2** [comment]
This is python. I'll adjust

**Comment by ebridge2** [comment]
As a side note, does it make sense to normalize the images by the mean of each image? Ie, for registration, our reference template is going to have much different intensities than the thing we are registering, so divide each image by the max signal intensity prior to computing

**Comment by ebridge2** [comment]
![image](https://cloud.githubusercontent.com/assets/8883547/16326881/a07c98e0-3998-11e6-96e1-08715cb665e7.png)

forgot to adjust dot size

**Comment by ebridge2** [comment]
@jovo 

![image](https://cloud.githubusercontent.com/assets/8883547/16326952/3a551d84-3999-11e6-8a0e-8f3fd0b67eee.png)

**Comment by jovo** [comment]
maybe add some jitter.
alpha channel didn't do it for me.

On Thu, Jun 23, 2016 at 11:21 PM, ebridge2 notifications@github.com wrote:

> @jovo https://github.com/jovo
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/8883547/16326952/3a551d84-3999-11e6-8a0e-8f3fd0b67eee.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/Upward-Spiral-Science/fngs/issues/19#issuecomment-228249340,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcoiUBS0ooNO2cZAFcjGwlRv-MKAPks5qO01BgaJpZM4I7BES
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by ebridge2** [comment]
btw @jovo forgot to upload this. Looks pretty good to me. x is just (sliceid + rand) where rand is a random float btwn 0 and 1. I adjusted how we were normalizing for the mse comparison slightly which is why the middle values are no longer just super low. 
![image](https://cloud.githubusercontent.com/assets/8883547/16353536/cabc259c-3a49-11e6-8962-c5644348ef37.png)

**Comment by jovo** [comment]
yah, way better i think.

On Fri, Jun 24, 2016 at 8:25 PM, ebridge2 notifications@github.com wrote:

> btw @jovo https://github.com/jovo forgot to upload this. Looks pretty
> good to me.
> [image: image]
> https://cloud.githubusercontent.com/assets/8883547/16353536/cabc259c-3a49-11e6-8962-c5644348ef37.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/Upward-Spiral-Science/fngs/issues/19#issuecomment-228495350,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcroyduV4e9svhCwuFETMpSN8CJF4ks5qPHWFgaJpZM4I7BES
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
