### ISSUE TITLE
Nifti viewer in browser for mean, std, and snr images

### ISSUE THREAD

**Issue by ebridge2** [Upward-Spiral-Science/fngs#21]
Will allow users to easily add the MNI or aligned MPRAGE brains to a quality control HTML page to see the effectiveness of registration on the brain, and also serve as the best way to visualize quality control while giving users incentive to use the service as this QC would be way more user friendly than that of other services

**Comment by jovo** [comment]
we have that already: http://viz.neurodata.io/KKI2009v03/
especially, once data are ingested into neurodata,
which should certainly be part of your pipeline.

On Fri, Jun 24, 2016 at 4:39 PM, ebridge2 notifications@github.com wrote:

> Will allow users to easily add the MNI or aligned MPRAGE brains to a
> quality control HTML page to see the effectiveness of registration on the
> brain, and also serve as the best way to visualize quality control while
> giving users incentive to use the service as this QC would be way more user
> friendly than that of other services
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Upward-Spiral-Science/fngs/issues/21, or mute the
> thread
> https://github.com/notifications/unsubscribe/AACjcpsPbZR58civbxVkDoClRejMO-ZHks5qPECVgaJpZM4I-G3B
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
