### ISSUE TITLE
Better registration procedure

### ISSUE THREAD

**Issue by ebridge2** [Upward-Spiral-Science/fngs#22]
Existing linear (only) registration like those used by ndmg lead to a loss of data for some subjects. Below is an example of what I am referring to; goal is to implement the procedure for registration recommended by FSL found at http://web.mit.edu/fsl_v5.0.8/fsl/doc/wiki/FNIRT(2f)UserGuide.html#Example_uses.

![image](https://cloud.githubusercontent.com/assets/8883547/16360285/e729a83e-3b26-11e6-8ef5-dc4d944aa8cc.png)

Notice the patch of lost data starting at the top and ending just below the L/R axis.

**Comment by jovo** [comment]
i don't understand, let's discuss.

On Sat, Jun 25, 2016 at 10:47 PM, ebridge2 notifications@github.com wrote:

> Existing linear (only) registration images like those used by ndmg lead to
> a loss of data for some subjects. Below is an example of what I am
> referring to; goal is to implement the procedure for registration
> recommended by FSL found at
> http://web.mit.edu/fsl_v5.0.8/fsl/doc/wiki/FNIRT(2f)UserGuide.html#Example_uses
> .
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/8883547/16360283/babfd48a-3b26-11e6-9b8d-3b67a09d9665.png
> Notice the patch of lost data starting at the top and ending just below
> the L/R axis.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Upward-Spiral-Science/fngs/issues/22, or mute the
> thread
> https://github.com/notifications/unsubscribe/AACjcslULkbPgSlqx_nxhT0KhM7M9A50ks5qPehHgaJpZM4I-eSY
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by ebridge2** [comment]
it's kind of hard to see there, but im going thru QC on the dataset and registration fails in some locations (mostly the edges of the brain, like this slice which is the bottom of the brain). i think using fnirt is more robust for fmri so ill try that once i have an initial run complete.

**Comment by jovo** [comment]
to discuss tom.

On Sun, Jun 26, 2016 at 2:55 PM, ebridge2 notifications@github.com wrote:

> it's kind of hard to see there, but im going thru QC on the dataset and
> registration fails in some locations (mostly the edges of the brain, like
> this slice which is the bottom of the brain). i think using fnirt is more
> robust for fmri so ill try that once i have an initial run complete.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/Upward-Spiral-Science/fngs/issues/22#issuecomment-228616336,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcsmKq6IrsfoPz0s1S2SuubssrNjOks5qPssygaJpZM4I-eSY
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by ebridge2** [comment]
yep; here's another picture that makes it a little more obvious what is going wrong (for reference tomorrow). 

![image](https://cloud.githubusercontent.com/assets/8883547/16364331/b891dc08-3bb2-11e6-87d4-56f8c5d7cec3.png)

This is the mean functional image overlayed with the anatomical image for another subject. I have a good idea of an alternative to try that we can discuss tomorrow.
