### ISSUE TITLE
issue for July 25

### ISSUE THREAD

**Issue by mlee156** [Upward-Spiral-Science/fngs#28]
@alee156 
1. Talk to Alex
- [x]  2D and 3D local and global histogram
- [x] Clarity 2d above
- [x]  Clarity 3d above
- [x] final product should be 13 CLARITY brains with local histograms in javascript

@ewalke31 
- [x] compute discriminability with all parameters for AR(2) and AR(3)
- [x] apply rank transform, sparsify, low rank to timeseries to analyze effects
- [x] show actual AR computation matrices
- [x] estimate parameters & test prediction accuracy
- [x] apply Kalman filtering to timeseries
- [x] investigate nonlinear methods if time (didn't have time this week)

@ebridge2
- [x] try some FNIRT stuff. Deliverable: FNIRT registered brain compared to our FLIRT registered brains (existing) qc wise, and mnr statistic with a pipeline implementing FLIRT.
- [x] add code for improving generalizability of algorithms (ie, adding scripts that automatically register things like labelled atlases if they are not in the correct brain space, etc) to allow people to pass templates, masks, brains, and labels in all sorts of different brain spaces and still receive a valid result. Deliverable: algorithms that do this, and qc figures to show that it works.
  I've come under the belief that this is relatively impossible to do automatically, and the only way to do it is to know ahead of time what space your dependencies are in and convert accordingly before hand. Would be cool down the line to have some way of detecting the brain space (MNI vs Talaraich generally, for atlases and masks) and to then automatically know which transform to apply (ex, if we pass an atlas in Talaraich, to know to apply tal2mni in the FSL FLIRT package)
- [x] compare CPAC to us with HCP dataset with direct comparison of figures. Deliverable: a file containing a direct comparison of QC figures from CPAC to us. 
  link: https://docs.google.com/document/d/1unLkdMU-KhaOBHNLfk6l9NLXOif2DY7Qp6d-S2T-lmU/edit?usp=sharing
- [x] run 3 datasets (KKI21, NKI24-TR=645, and one of the BNUs) through pipeline, debug, and give overall pipeline feedback. Deliverable: folder on Gdrive containing QC for all these datasets, and 1x2 plot with distance matrix/subject relationship kde. 
  Ran NKI, BNU1, DC1, HNU1, and SWU4. Run interrupted by redoing of office space, however, NKI and BNU1 are complete with the other 3 almost finished. 
- [x] learn how to reorganize into callable packages/reorganize for package declaration. will allow us to use ndmg when we need graphs on AMIs/other computers in the future. 
- [x] read dempster 1977 and calhoun 2016.
- [x] run data for Da.

**Comment by jovo** [comment]
@ebridge2 add your stuff.

**Comment by ebridge2** [comment]
whoops; sorry, forgot. good?

**Comment by jovo** [comment]
Yah

On Monday, July 11, 2016, ebridge2 notifications@github.com wrote:

> whoops; sorry, forgot. good?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/Upward-Spiral-Science/fngs/issues/28#issuecomment-231927263,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcpg1hHK1voSVl6HhHqTIZqCl3O0Wks5qUwftgaJpZM4JJvQ2
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by ebridge2** [comment]
@jovo I have qc for the BNU1, BNU2, NKI645, and SWU4 datasets thru our pipelines and am trying to put it in the google drive, but we are out of space. Where should I put it instead?

**Comment by jovo** [comment]
can you clean up google drive?

**Comment by ebridge2** [comment]
each subject produces about 100-130 MB of QC. We have ~120 subjects for each of the 3 BNUs, ~450 for SWU, and ~40 for NKI, for a total of ~850 subjects, which equates to a storage need of around 100 gigs for the qc of everything together, while our drive is only 15 gigs total.

**Comment by ebridge2** [comment]
I'm thinking a shared location on brainstore might work better? but then the disadvantage obviously is that everything would need to be downloaded to be viewed.

**Comment by jovo** [comment]
we don't have space 
if you read the [docs](http://docs.neurodata.io/ndstore/)
you can ingest the data and also dynamically generate the QC images, 
rather than storing them

@aeus can help.

**Comment by ebridge2** [comment]
@alee156 close if this is completed, else move tasks to "Future goals" issue.
