### ISSUE TITLE
issues for 8/15

### ISSUE THREAD

**Issue by ewalke31** [Upward-Spiral-Science/fngs#32]
@ewalke31
- [x] simulate data
- [x] code univariate kalman filter
- [x] code univariate kalman smoother
- [x] test against previous value predictor
- [x] create r markdown for presentation
  http://upward-spiral-science.github.io/fngs/ewok_weekly/ewok_week_815.html
- [x] use existing code where possible
- [x] read style guide https://github.com/Upward-Spiral-Science/fngs/blob/master/status/organization.Rmd

@ebridge2
- [x] run/analyze a bunch of datasets with new pipeline. Deliverable: in slide show for the week.
- [x] explore EM algorithm and use Gui's notes
- [x] refactor memory analyses with convolution understanding, and use more efficient vector wise function calls (apply) Deliverable: https://github.com/neurodata/memory/blob/master/status/status_812.md
- [x] use M step with our pi vector for finding the covariance matrices of our sources. Deliverable: failed to deliver here; learning EM enough to feel confident that I understood what was really going on at the heart of the algorithm took some serious time (and youtube videos!). Refined goal is to have own implementation of GMM by next week, and then use M step with our pi vector possibly also next week/the following week. 
- [x]  compare covariance matrices of our sources with old method for tfMRI
- [ ] fMRI dataset wise QC repo
- [x] Memory performance analysis of fngs. Deliverable: in slide show for week.
- [x] show Eric Perlman qsub_braincloud repo. Deliverable: slack'd

@alee156
- [x] Demonstrable SIMPLE models and proofs for each:
- [x] 2D HISTEQ AND ADAPTEQ
- [x] 3D HISTEQ AND ADAPTEQ

**Comment by jovo** [comment]
don't forget to simulate data too :) that is the simplest, and therefore, most important thing to do first!

**Comment by jovo** [comment]
see google's R style code and probably include it or at least link to it.

@ewalke31 @ebridge2 @alee156
