### ISSUE TITLE
Goals for 8/22

### ISSUE THREAD

**Issue by mlee156** [Upward-Spiral-Science/fngs#34]
@jovo 

@ewalke31 
- [x] code multivariate kalman filter and smoother and present in r markdown
- [x] work with @ebridge2 on EM implementation Deliverable: an understandable proof, as well as a simple and one complex example that it works.

http://upward-spiral-science.github.io/fngs/reveal/week_822.html#/11

@ebridge2
- [x] implement EM for GMM. Deliverable: an understandable proof, as well as a simple and one complex example that it works. 
- [x] prove/implement multivariate KF. Deliverable: an understandable proof, as well as a simple and one complex example that it works. 
- [x] memory. look over new and old code, debug, error check, etc. Convince myself that what we were doing before is either explicitly wrong for some reason/reasons, show that using new code we can replicate old performance in reliable way (through minor modification, and get same result, using function-based analysis). show summary plots comparing the two. 
- [x] switch out linear/quadratic detrending for high pass filtering. This also will remove low frequency drifting, and not have the issue that it forces a model to the data. Research has shown that high pass filtering is the way to go over linear/quadratic detrending, so this week will be inspecting that for nuisance. 

@alee156
Create Jupyter Notebook that shows that the below works:
- [x] 2D general histogram equalization on a Clarity image 
    -[ ] Deliverable: Two images that show this works
- [x] 2D local histogram equalization on a Clarity image
    -[x] Deliverable: Two images that show this works
- [ ] Full Volume general histogram equalization on a full Clarity volume
    -[ ] Deliverable: Two images that show this works
- [ ] local histogram equalization on a full Clarity volume
    -[ ] Deliverable: Two images that show this works

**Comment by jovo** [comment]
@ebridge2 @ewalke31 @alee156 this is progress in terms of the issue.

but, it is time to start thinking more carefully about how you will convince yourselves and one another that the code you are writing is correct.  so, prior to doing anything else, please make much more clear definition of done, and in particular: _how will you know that your code works_, 
this is a very important thing to think about _before_ writing any code, 
and encourages thinking really clearly and simply about what to do.

so, please revise, providing details for which experiments you will perform, which metrics/figures you will generate, and what you expect the outcomes to be.  then, we can check to see whether the outcomes you predicted are the ones you got.  

if this makes sense, please tell team orange-panda too.
thank you, j
