### ISSUE TITLE
Week 3

### ISSUE THREAD

**Issue by mlee156** [Upward-Spiral-Science/fngs#4]
@jovo 
### @ewalke31
- [x] read ch 6-7
- [x] add corresponding exercises to R markdown file
  [R markdown](http://upward-spiral-science.github.io/ugrad-data-design-team-0/reveal/ewok_week_612.html#chapter-6)
### @ebridge2
- [x] have simple pipeline developed (no clue how long this will take, hopefully a week though? raw data -> motion correction -> registration -> downsampling -> graph generation)
- [x] for each step of pipeline completed completed, have detailed quality control that is outlined in presentation complete (qualitative and quantitative measures for each step)
- [ ] run simple pipeline on one dataset (KKI21 for simplicity) and perform discriminability on the results, ranked and unranked
- [x] deliverable 1 (to be shown in presentation): example of a motion corrected graph, along with the QC outlined in last week's presentation
- [x] deliverable 2 (to be shown in presentation): example of a registered brain, along with the quality control outlined in last week's presentation
- [x] deliverable 3 (to be shown in presentation): example of a correlation matrix for one brain
- [ ] deliverable 4 (not in presentation): above 3 deliverables for an entire dataset (KKI21)
- [ ] deliverable 5 (to be shown in presentation): 2x column plot, with distance matrix for all the graphs in dataset (KKI21) with discriminability as title, and other as kde for intra and inter subject relationship, with hellinger distance as title
- [x] deliverable 6: have QC performed to the metrics offered by http://cbs.fas.harvard.edu/science/core-facilities/neuroimaging/information-investigators/qc

note: some of these goals may take a week and a half to complete, but I will try to get them for next meeting
### @alee156
- [ ] continue three.js tutorials
- [ ] create 3D scatter plots for Clarity using three.js
- [ ] try to incorporate atlas in scatter plots for reference

**Comment by jovo** [comment]
good start.
each action requires a "measurable deliverable".  so, "reading" does not count.  you need to commit to doing something that i can then confirm you did.
