### ISSUE TITLE
decide whether skullstripping could be an advantageous next step

### ISSUE THREAD

**Issue by ebridge2** [Upward-Spiral-Science/fngs#6]
skullstripping could be advantageous, as it will make QC far more robust. different imaging modalities have different contrasts of the skull in particular, so checking how effective two things line up would be far more robust if we were to simply binarize the images, however non-skullstripped images cannot be binarized as the brain has not exclusively been extracted (so there are small spikes all throughout the image from scanner noise that cannot be removed without skullstripping). I have some good ideas for QC that would require skullstripping is why I mention this. @jovo

**Comment by jovo** [comment]
it is certainly not in the first stage of development.
maybe after getting something working, it is worth considering as a feature to improve results.

**Comment by ebridge2** [comment]
yah ik, i was just reading and found that that was a big advantage of skullstripping and had some ideas of how to do it, so I figured I'd leave it here for future reference after we have something working
