### ISSUE TITLE
Functionality to add to web service

### ISSUE THREAD

**Issue by ebridge2** [Upward-Spiral-Science/fngs#62]
- [x] results page with QC summary in explore section, and ability to download a folder containing processed fMRI results.
- [x] return error if subject files already in folder for files, or delete data associated with subject when deleting subject (right now if the subject is deleted and then added back, the scans will be named in non-standard nifti format).
- [ ] figure out if possible to make some way to visualize pipeline progress (is it possible to forward stdout for the pipeline live to the user? maybe a feature to add down the line, but just explore what's out there.).

stretch goal:
- [x] figure out how to put the website up on cortex in a docker.

**Comment by ebridge2** [comment]
l

**Comment by jovo** [comment]
seems good to me
