### ISSUE TITLE
Goals 11/21

### ISSUE THREAD

**Issue by ebridge2** [Upward-Spiral-Science/fngs#63]
@ebridge2

| Status | Task | Deliverable |
| ------------- | ------------- | ------------- |
| 👍  | [Downloadable results](https://github.com/NeuroDataDesign/fngs/issues/67) | Deliverable: ability to download results from web service. |
| 👍  | [Explorable QC](https://github.com/NeuroDataDesign/fngs/issues/64) | Deliverable: ability to explore QC integrated with the webpage. |
| 👍  | [Errors when uploading data](https://github.com/NeuroDataDesign/fngs/issues/65) | Deliverable: demonstrate what happens when a duplicate subject is uploaded, then deleted, then uploaded, then analyzed (it throws an error now, make sure that doesn't happen by deliverable date). |
| 👍 | [Overview of CompCorr](https://github.com/NeuroDataDesign/fngs/issues/57) | Deliverable: more rigorous overview of CompCorr (no code, just thorough pseudo for the algorithm and rough ideas for simulations; this week is mostly about reading and figuring out how to make it work with our pipeline). [progress report](https://github.com/NeuroDataDesign/fngs/blob/master/reveal/pdfs/progress_report.pdf) |

stretch goals

| Status | Task | Deliverable |
| ------------- | ------------- | ------------- |
| 👍  | [Update pull request](https://github.com/neurodata/ndmg/pull/119) | Deliverable: pull request to ndmg. |

@ewalke31 @02agarwalt 

| Status | Task | Deliverable |
| ------------- | ------------- | ------------- |
|👍 | [Write pseudocode for KFS EM Discriminability code](https://github.com/NeuroDataDesign/fngs/issues/69) | [Pseudocode](http://neurodatadesign.github.io/fngs/tanay/pseudocode_of_process.pdf) |
|👍 | [Perform simulations for KFS EM discriminability](https://github.com/NeuroDataDesign/fngs/issues/70) | [R markdown w/ simulations](http://neurodatadesign.github.io/fngs/ewok_weekly/KFSv2.html) |
| :x: | [If time, based on simulations, correct any errors we made with calculating discriminability on real data](https://github.com/NeuroDataDesign/fngs/issues/71) | R markdown w/ results (realdata.md) |

**Comment by ebridge2** [comment]
@jovo @gkiar will these goals complete our deliverable of the web service itself for the final project (ie, having analysis and browsing of results for users?) just trying to gauge exactly what does/does not need to be in there for the final web service just so I can prioritize all of them in time.

also, @ewalke31 @02agarwalt add yo stuff.

**Comment by jovo** [comment]
@ebridge2 
i don't want any choices in the pipeline, we choose for them.
if you want them to have multiple atlases, we will do all of them.

@ewalke31 we should have clarified more explicitly earlier, doc files are not an acceptable format, everything in this class must be web-readable.

@gkiar please update syllabus accordingly.

**Comment by jovo** [comment]
@ebridge2 
- [ ] upon downloading, what do you get? please clarify?
- [ ] how do we know whether things look good?
- [ ] use plot.ly + ggplot2 for figs
- [ ] show the whole pipeline schematic
- [ ] deliverables are figures/statistics

@ewalke31 
- [ ] what did we learn? simplify, look at it.
- [ ] let's look at the A matrices?

**Comment by mnatenz1** [comment]
@ewalke31 At the end of the "Perform simulations for KFS EM discriminability" document, you explain how we know that the estimation algorithm worked poorly. However, I wasn't clear on Why the estimation algorithm performed poorly.

**Comment by rmarren1** [comment]
@ebridge2  what port on cortex? couldn't see enough to get feedback from far away
also for the progress report, I find it neater to explain which symbol means what in a paragraph above the algorithm then just have the symbols as the input / output in the latex

**Comment by ebridge2** [comment]
@rmarren1 8061
