### ISSUE TITLE
Goals 12/5

### ISSUE THREAD

**Issue by ewalke31** [Upward-Spiral-Science/fngs#72]
@ebridge2

| Status | Task | Deliverable |
| ------------- | ------------- | ------------- |
| 👍   |  [workflows and algorithm details](https://github.com/NeuroDataDesign/fngs/issues/74) | Add a workflow of the entire pipeline, and link to external resources as necessary. |
| :x:  | [tGMM](https://neurodatadesign.github.io/fngs/reveal/pdfs/experiments_on_dataset.html) | tGMM deliverable for preparation of sending to Kara and Susan.  |
| 👍  | [nuisance correction](https://github.com/NeuroDataDesign/fngs/blob/master/reveal/pdfs/ML_proposal.pdf) | Nuisance Correction Progress goals: have implementation and quality control finished. Waiting on Tanay for simulation results. |

http://128.220.11.5:8061/algorithms/

@ewalke31 @02agarwalt 

| Status | Task | Deliverable |
| ------------- | ------------- | ------------- |
| ⌛️ | [Reorganize and condense QC code](https://github.com/NeuroDataDesign/fngs/issues/79) | [code & plots](http://neurodatadesign.github.io/fngs/ewok_weekly/ewok_weekly_1205.html) |

**Comment by jovo** [comment]
seems good to me.
@gkiar ?

**Comment by gkiar** [comment]
@ewalke31 @02agarwalt we want your tool to become part of the web service, as well. So let's also prioritize integrating your tool with @ebridge2 's stack.

**Comment by gkiar** [comment]
sorry this is so late, I wrote it two days ago but forgot to post

**Comment by ewalke31** [comment]
@gkiar @jovo

**Comment by jovo** [comment]
- [ ] **always** needs links to everything
- [ ] verify your implementation of nuisance yields the same answers, probably requires running part of benchmark.md, run their unit tests.
- [ ] where is the erosion stuff coming from?
- [ ] collect all the figures (not brain images) into a single multipanel fig or page per scan
- [ ] algorithms.md for any of the steps in the pipeline are good things to have
- [ ] statistic for tGMM?
- [ ] do the correlation matrices look very different?
- [ ] what don't you understand about a ROC curve? it needs a ground truth, so i'm not seeing how it is appropriate?
- [ ] don't do images in plotly, we will do them in ndstore/ndviz
